-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 18:55:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FinanceAdvisorDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FinanceAdvisorDB` ;

-- -----------------------------------------------------
-- Schema FinanceAdvisorDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinanceAdvisorDB` DEFAULT CHARACTER SET utf8 ;
USE `FinanceAdvisorDB` ;

-- -----------------------------------------------------
-- Table `FinanceAdvisorDB`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinanceAdvisorDB`.`tag` ;

CREATE TABLE IF NOT EXISTS `FinanceAdvisorDB`.`tag` (
  `idtag` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtag`),
  UNIQUE INDEX `idtag_UNIQUE` (`idtag` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `FinanceAdvisorDB`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinanceAdvisorDB`.`vendor` ;

CREATE TABLE IF NOT EXISTS `FinanceAdvisorDB`.`vendor` (
  `idvendor` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idvendor`),
  UNIQUE INDEX `idvendor_UNIQUE` (`idvendor` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 200
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `FinanceAdvisorDB`.`tag_to_vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinanceAdvisorDB`.`tag_to_vendor` ;

CREATE TABLE IF NOT EXISTS `FinanceAdvisorDB`.`tag_to_vendor` (
  `idtag_to_vendor` INT(11) NOT NULL AUTO_INCREMENT,
  `vendor` INT(11) NULL DEFAULT NULL,
  `tag` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idtag_to_vendor`),
  UNIQUE INDEX `idtag_to_vendor_UNIQUE` (`idtag_to_vendor` ASC),
  INDEX `vendor_idx` (`vendor` ASC),
  INDEX `tag_fk_idx` (`tag` ASC),
  CONSTRAINT `vendor_fk`
    FOREIGN KEY (`vendor`)
    REFERENCES `FinanceAdvisorDB`.`vendor` (`idvendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_fk`
    FOREIGN KEY (`tag`)
    REFERENCES `FinanceAdvisorDB`.`tag` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 162
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `FinanceAdvisorDB`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinanceAdvisorDB`.`transaction` ;

CREATE TABLE IF NOT EXISTS `FinanceAdvisorDB`.`transaction` (
  `transactionid` INT(11) NOT NULL AUTO_INCREMENT,
  `value` FLOAT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `card` MEDIUMTEXT NULL DEFAULT NULL,
  `vendor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`transactionid`),
  UNIQUE INDEX `idnew_table_UNIQUE` (`transactionid` ASC),
  INDEX `vendor_fk_idx` (`vendor` ASC),
  CONSTRAINT `vendor_fk`
    FOREIGN KEY (`vendor`)
    REFERENCES `FinanceAdvisorDB`.`vendor` (`idvendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 887
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
